// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWHNorthwindOrders.Models.DWHNorthwindOrders.ModelsOrders;

public partial class FactClienteAtendido
{
    public int ClienteAtendidoKey { get; set; }

    public int EmployeeKey { get; set; }

    public int NumeroDeClientes { get; set; }
}