// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDWHNorthwindOrders.Models.Models;

public partial class NorthwindContext : DbContext
{
    public NorthwindContext(DbContextOptions<NorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<VwClienteAtendido> VwClienteAtendidos { get; set; }

    public virtual DbSet<VwOrder> VwOrders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VwClienteAtendido>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VwClienteAtendido", "DWH");

            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasMaxLength(31);
        });

        modelBuilder.Entity<VwOrder>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VwOrders", "DWH");

            entity.Property(e => e.ClienteId)
                .IsRequired()
                .HasMaxLength(5)
                .IsFixedLength()
                .HasColumnName("ClienteID");
            entity.Property(e => e.ClienteNombre)
                .IsRequired()
                .HasMaxLength(40);
            entity.Property(e => e.Country).HasMaxLength(15);
            entity.Property(e => e.EmpleadoId).HasColumnName("EmpleadoID");
            entity.Property(e => e.EmpleadoNombre)
                .IsRequired()
                .HasMaxLength(31);
            entity.Property(e => e.OrdenId).HasColumnName("OrdenID");
            entity.Property(e => e.TransportistaId).HasColumnName("TransportistaID");
            entity.Property(e => e.TransportistaNombre)
                .IsRequired()
                .HasMaxLength(40);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}