// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWHNorthwindOrders.Models.Models;

public partial class VwClienteAtendido
{
    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public int? NumeroDeClientes { get; set; }
}